"""Pydantic models describing student personalisation profiles."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class StudentProfileBase(BaseModel):
    """Shared fields across student profile representations."""

    user_id: str = Field(..., description="Supabase auth identifier")
    strengths: List[str] = Field(default_factory=list, description="Subjects/topics with high mastery")
    weaknesses: List[str] = Field(default_factory=list, description="Subjects/topics needing improvement")
    subject_proficiency: Dict[str, float] = Field(
        default_factory=dict,
        description="Normalized proficiency score per subject (0.0-1.0)",
    )
    topic_proficiency: Dict[str, float] = Field(
        default_factory=dict,
        description="Normalized proficiency score per topic (0.0-1.0)",
    )
    preferred_styles: Dict[str, int] = Field(
        default_factory=dict,
        description="Counts of explanation styles the student responds well to",
    )
    recent_topics: List[str] = Field(
        default_factory=list,
        description="Most recent topics engaged with (ordered, unique)",
    )
    last_interaction_at: Optional[datetime] = Field(
        default=None,
        description="When the profile was last updated",
    )
    metadata: Dict[str, Any] = Field(default_factory=dict)


class StudentProfileCreate(StudentProfileBase):
    """Payload used when creating a new student profile."""

    pass


class StudentProfileUpdate(BaseModel):
    """Partial update payload for a student profile."""

    user_id: str
    strengths: Optional[List[str]] = None
    weaknesses: Optional[List[str]] = None
    subject_proficiency: Optional[Dict[str, float]] = None
    topic_proficiency: Optional[Dict[str, float]] = None
    preferred_styles: Optional[Dict[str, int]] = None
    recent_topics: Optional[List[str]] = None
    last_interaction_at: Optional[datetime] = None
    metadata: Optional[Dict[str, Any]] = None


class StudentProfileRecord(StudentProfileBase):
    """Stored representation returned from the repository."""

    id: Optional[str] = Field(default=None, description="Primary key generated by Supabase")
    created_at: Optional[datetime] = Field(default=None)
    updated_at: Optional[datetime] = Field(default=None)

    class Config:
        from_attributes = True


class SubjectInsight(BaseModel):
    """Subject-level proficiency insight for dashboard visualisation."""

    subject: str
    proficiency: float


class StudentDashboardView(BaseModel):
    """Aggregated dashboard representation for a student's progress."""

    user_id: str
    strengths: List[str]
    weaknesses: List[str]
    preferred_styles: Dict[str, int]
    dominant_style: Optional[str]
    subject_focus: List[SubjectInsight]
    recent_topics: List[str]
    active_streak_days: int
    last_interaction_at: Optional[datetime]
    alerts: List[str]
