// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqfqdpemaihdtpzyuevl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZnFkcGVtYWloZHRwenl1ZXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjE4ODgsImV4cCI6MjA2NTk5Nzg4OH0.TItHSnChgBebZFQ_Vx4o5oLALNCy5Z0hbpLLd4cgo2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);